import {scale} from './fonts';

const theme = {
  roundness: 28,
  colors: {
    primary1: '#000000',
    secondary: '#DBE9E3',
    cream: '#F7F4EF',
    black: '#000',
    white: '#FFF',
    white1: '#F6F6F6',
    white2: '#E4E4E4',
    lightGray: '#C4C4C4',
    mediumGray: '#ededed',
    darkGray: '#868686',
    lightBlue: '#B1E0F0',
    lightBlue1: '#CBE5F2',
    red: '#CF4A57',
    lightRed: '#FFB7B2',
    lightRed1: '#FFD9D9',
    green: '#E2F0CB',
    yellow: '#FFE899',
    purple: '#C7CEEA',
    primary: '#000000',
    back: '#EBEBEB',
  },
  fontSizes: {
    h0: scale(32),
    h01: scale(26),
    h2: scale(22),
    h1: scale(24),
    h3: scale(20),
    h4: scale(18),
    text: scale(16),
    subtext: scale(14),
    small: scale(12),
    sosmall: scale(10),
    terms:scale(8),
  },
  fontFamilies: {
    h0: 'Circular Std Book',
    h01: 'Circular Std Medium',
    h1: 'Circular Std Medium',
    h2: 'Circular Std Medium',
    h3: 'Circular Std Medium',
    h4: 'Circular Std Book',
    text: 'Circular Std Book',
    subtext: 'Circular Std Book',
    small: 'Circular Std Book',
    sosmall: 'Circular Std Book',
    terms: 'Circular Std Book',
  },
};

export default theme;
